runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: Proyek Deploy Aplikasi Profile/index.html
  upload: Proyek Deploy Aplikasi Profile/index.html

- url: /(.*)
  static_files: Proyek Deploy Aplikasi Profile/\1
  upload: Proyek Deploy Aplikasi Profile/(.*)
