runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: myportofolio/index.html
  upload: myportofolio/index.html

- url: /(.*)
  static_files: myportofolio/\1
  upload: myportofolio/(.*)
